//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Hrvoje_Trudnoca_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class RekreacijaPovijest
    {
        public int IdSetnja { get; set; }
        public Nullable<int> IdKorisnika { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Setnja { get; set; }
        public bool KodKuce { get; set; }
        public System.DateTime SysStartTime { get; set; }
        public System.DateTime SysEndTime { get; set; }
    }
}
