//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Hrvoje_Trudnoca_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrudnocaAppEntities : DbContext
    {
        public TrudnocaAppEntities()
            : base("name=TrudnocaAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Beba> Beba { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<Medicina> Medicina { get; set; }
        public virtual DbSet<NajdraziUdarci> NajdraziUdarci { get; set; }
        public virtual DbSet<Registar> Registar { get; set; }
        public virtual DbSet<Rekreacija> Rekreacija { get; set; }
        public virtual DbSet<Udarci> Udarci { get; set; }
        public virtual DbSet<Velicina> Velicina { get; set; }
        public virtual DbSet<MedicinaPovijest> MedicinaPovijest { get; set; }
        public virtual DbSet<RekreacijaPovijest> RekreacijaPovijest { get; set; }
    }
}
