//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TBP_Hrvoje_Trudnoca_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Udarci
    {
        public int Id { get; set; }
        public System.DateTime DatumPocetak { get; set; }
        public System.DateTime DatumKraj { get; set; }
        public Nullable<int> Udarci1 { get; set; }
        public Nullable<int> IdKorisnika { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
